### ISSUE TITLE
isStarred boolean not present in component resource

### ISSUE THREAD

**Issue by kavi87** [seedstack/hub#78]
All in the title.

**Comment by pith** [comment]
## Using the star link
When a component is starred by the user, the `star` link on the component resource is no more provided.

## Querying the user stars resource

Another mean to know if a component is starred is to do an HTTP GET on the resource `/user/stars/{componentId}`

```json
{
    "isStarred": true
}

```
or 

```json
{
    "isStarred": false
}
```
